import js from "@eslint/js";
import globals from "globals";

export default [
  js.configs.recommended,
  {
    files: ["**/*.js", "build.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...globals.node,
        Office: "readonly",
        Word: "readonly",
        Excel: "readonly",
        PowerPoint: "readonly",
        mammoth: "readonly",
        pdfjsLib: "readonly",
        JSZip: "readonly",
        marked: "readonly",
        hljs: "readonly",
        DOMPurify: "readonly",
        // Globals lintas-file yang didefinisikan di script.js / ui-extras.js
        showToast: "readonly",
        addBotMessage: "readonly",
        addUserMessage: "readonly",
        callGeminiAPI: "readonly",
        escapeHtml: "readonly",
        switchMode: "readonly",
        currentLang: "readonly",
        saveToHistory: "readonly",
        renderHistory: "readonly",
        renderPresets: "readonly",
        setupExtraPanels: "readonly",
        getOfflineCache: "readonly",
        cacheOffline: "readonly",
        addRatingButtons: "readonly",
        runPowerPointSlideGen: "readonly",
        getBimbinganPrefix: "readonly",
        clearFolderContext: "readonly",
        setupQuickActions: "readonly",
        updateNetworkStatus: "readonly",
        insertIntoDocument: "readonly",
        fileToText: "readonly",
        safeHtmlForWord: "readonly",
        proofreadingMendalam: "readonly",
        openOutlineBuilder: "readonly",
        toggleBimbinganSkripsi: "readonly",
        analisisRegresi: "readonly",
        interpretasiStatistik: "readonly",
        insertTemplateTabel: "readonly",
        slideFromUploadedFile: "readonly",
        parafraseTeks: "readonly",
        generateOutline: "readonly",
        toggleOutlineChapter: "readonly",
        expandChapter: "readonly",
        insertOutlineToDoc: "readonly",
        terapkanValidasiData: "readonly",
        terapkanTemaSlide: "readonly",
        startPracticeTimer: "readonly",
        stopPracticeTimer: "readonly",
        resetPracticeTimer: "readonly",
        applyBuiltinTemplate: "readonly",
        insertCitation: "readonly",
        loadHistoryItem: "readonly",
        clearHistory: "readonly",
        usePreset: "readonly",
        deletePreset: "readonly",
        saveCurrentAsPreset: "readonly",
        rateResponse: "readonly",
        copyMessageText: "readonly",
        tourNext: "readonly",
        tourPrev: "readonly",
        closeTour: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }],
      "no-empty": "warn",
      // File frontend adalah skrip browser terpisah yang berbagi satu global scope
      // saat runtime (fungsi lintas-file). Re-deklarasi & assignment global adalah
      // pola yang sah di sini, sehingga aturan berikut dimatikan untuk menghindari
      // false positive.
      "no-redeclare": "off",
      "no-global-assign": "off",
    },
  },
  {
    files: ["backend/**/*.js"],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      "no-console": "off",
    },
  },
  {
    ignores: ["node_modules/**", "backend/node_modules/**", "*.min.js", "index.html"],
  },
];
